- name: Setup kubectl, Helm and install ArgoCD & Prometheus with user credentials
  hosts: server
  become: true
  become_user: root

  vars_files:
    - ../inventory/group_vars/server.yml
    
  vars:
    aws_region: ap-northeast-2
    cluster_name: "{{ (lookup('file', '../../output.json') | from_json).eks_cluster_name.value }}"
    argocd_namespace: argocd
    prometheus_namespace: monitoring
    helm_version: v3.14.2
    ack_system_namespace: ack-system

  tasks:
    - name: Install dependencies
      become_user: root
      apt:
        name:
          - curl
          - unzip
          - gnupg
          - software-properties-common
          - ca-certificates
        update_cache: yes

    - name: Download kubectl
      become_user: root
      shell: |
        curl -LO https://dl.k8s.io/release/v1.32.0/bin/linux/amd64/kubectl
        chmod +x kubectl
        mv kubectl /usr/local/bin/kubectl
      args:
        chdir: /tmp
        creates: /usr/local/bin/kubectl

    - name: Create .kube directory
      file:
        path: /home/ubuntu/.kube
        state: directory
        mode: '0755'
        owner: ubuntu
        group: ubuntu

    - name: Set kubeconfig using AWS CLI with explicit credentials
      command: >
        aws eks update-kubeconfig
        --region {{ aws_region }}
        --name {{ cluster_name }}

    - name: Download kubeseal binary
      get_url:
        url: https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.25.0/kubeseal-0.25.0-linux-amd64.tar.gz
        dest: /tmp/kubeseal.tar.gz

    - name: Extract kubeseal binary
      unarchive:
        src: /tmp/kubeseal.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: Move kubeseal binary to /usr/local/bin
      become_user: root
      copy:
        remote_src: yes
        src: /tmp/kubeseal
        dest: /usr/local/bin/kubeseal
        mode: '0755'

    - name: Create EKS Access Entry
      command: >
        aws eks create-access-entry
        --cluster-name {{ cluster_name }}
        --principal-arn arn:aws:iam::661393609088:role/ec2-jenkins-server-role
        --type STANDARD
        --username arn:aws:iam::661393609088:role/ec2-jenkins-server-role
      failed_when: false
      register: access_entry_result
      changed_when: "'created' in access_entry_result.stdout"

    - name: Associate EKS Access Policy
      command: >
        aws eks associate-access-policy
        --cluster-name {{ cluster_name }}
        --principal-arn arn:aws:iam::661393609088:role/ec2-jenkins-server-role
        --access-scope type=cluster
        --policy-arn arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy

    - name: Download Helm archive
      get_url:
        url: "https://get.helm.sh/helm-{{ helm_version }}-linux-amd64.tar.gz"
        dest: "/tmp/helm.tar.gz"

    - name: Extract and install Helm
      unarchive:
        src: "/tmp/helm.tar.gz"
        dest: "/tmp"
        remote_src: yes

    - name: Move Helm binary
      become_user: root
      copy:
        remote_src: yes
        src: "/tmp/linux-amd64/helm"
        dest: "/usr/local/bin/helm"
        mode: '0755'
    
    - name: Copy all Helm values files to remote server
      copy:
        src: ../resource/
        dest: /home/ubuntu/helm-values/
        owner: ubuntu
        group: ubuntu
        mode: '0644'
        directory_mode: '0755'

    - name: Add Sealed Secrets Helm repo
      command: helm repo add sealed-secrets https://bitnami-labs.github.io/sealed-secrets
    
    - name: Update all Helm repos
      command: helm repo update

    - name: Install Sealed Secrets Controller
      command: >
        helm upgrade --install sealed-secrets-controller sealed-secrets/sealed-secrets
        --namespace kube-system

    - name: Add ArgoCD Helm repo
      command: helm repo add argo https://argoproj.github.io/argo-helm

    - name: Create ArgoCD namespace
      command: kubectl create ns {{ argocd_namespace }}
      register: argocd_ns
      failed_when: false
      changed_when: "'created' in argocd_ns.stdout"
    
    - name: Check if ArgoCD already exists (via ServiceAccount)
      shell: kubectl get sa argocd-applicationset-controller -n {{ argocd_namespace }}
      register: argocd_exists
      failed_when: false
      changed_when: false

    - name: Install ArgoCD
      when: argocd_exists.rc != 0
      command: helm upgrade --install argocd argo/argo-cd -n {{ argocd_namespace }} -f /home/ubuntu/helm-values/argocd-values.yaml

    - name: Add Prometheus Helm repo
      command: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

    - name: Create Prometheus namespace
      command: kubectl create ns {{ prometheus_namespace }}
      register: prom_ns
      failed_when: false
      changed_when: "'created' in prom_ns.stdout"

    - name: Check if Prometheus is already exists
      shell: kubectl get sa prometheus-server -n {{ prometheus_namespace }}
      register: prometheus_exists
      failed_when: false
      changed_when: false

    - name: Install Prometheus
      when: prometheus_exists.rc != 0
      command: helm upgrade --install prometheus prometheus-community/prometheus -n {{ prometheus_namespace }} -f /home/ubuntu/helm-values/prometheus-values.yaml

    - name: Add OpenTelemetry Helm repository
      command: helm repo add open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts
      args:
        creates: /home/ubuntu/.helm-repo-open-telemetry-added

    - name: Update Helm repositories
      command: helm repo update

    - name: Create OpenTelemetry namespace
      command: kubectl create namespace opentelemetry-operator-system
      register: otel_ns
      failed_when: false
      changed_when: "'created' in otel_ns.stdout"
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config

    - name: Check if OpenTelemetry is already exists
      shell: kubectl get sa otel-collector -n opentelemetry-operator-system
      register: otel_exists
      failed_when: false
      changed_when: false

    - name: Install OpenTelemetry Collector
      when: otel_exists.rc != 0
      command: >
        helm upgrade --install otel-collector open-telemetry/opentelemetry-collector
        --namespace opentelemetry-operator-system
        -f /home/ubuntu/helm-values/otel-values.yml
        --wait
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config


    - name: Add ACK Helm repository
      command: helm repo add ack https://aws.github.io/eks-charts

    - name: Update Helm repositories
      command: helm repo update

    - name: Ensure ACK system namespace exists
      command: kubectl create namespace ack-system
      register: ack_ns
      failed_when: false
      changed_when: "'created' in ack_ns.stdout"
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config

    - name: Install ACK PrometheusService controller using kubectl apply
      command: >
        kubectl apply -k github.com/aws-controllers-k8s/prometheusservice-controller/config/default
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config


    
