server:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

repoServer:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

controller:
  resources:
    limits:
      cpu: 150m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

redis:
  resources:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 25m
      memory: 32Mi

dex:
  enabled: false  # 싱글 유저 환경에서는 비활성화

notifications:
  enabled: false  # Slack/email 알림 사용 안하면 꺼도 됨